title: "Coding Bridge"
description: "제 눈으로 보고, AI에게 물어봅니다."
url: "https://jameskwon07.github.io"
author: "James Kwon"
lang: ko

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink
permalink: /:year/:month/:day/:title/

# Collections
future: true
markdown: kramdown
highlighter: rouge

# SEO
google_site_verification: luOCqk7affdVSb9P9MdGCJAobhXntULF1sNcee2uyhI
twitter:
  username: jameskwon07
github:
  username: jameskwon07
